#!/usr/bin/env python3
"""Generate a C++ header that embeds corpus/wiki.test.raw as a byte array.

Usage: gen_corpus_header.py <source_file> <output_header>
"""
import hashlib
import os
import sys

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} <source_file> <output_header>", file=sys.stderr)
    sys.exit(1)

src_path, dst_path = sys.argv[1], sys.argv[2]

with open(src_path, "rb") as f:
    data = f.read()

sha256 = hashlib.sha256(data).hexdigest()
n = len(data)

os.makedirs(os.path.dirname(dst_path), exist_ok=True)

with open(dst_path, "w") as out:
    out.write("// Auto-generated by cmake/gen_corpus_header.py — do not edit.\n")
    out.write(f"// Source: {os.path.basename(src_path)}\n")
    out.write(f"// Size:   {n} bytes\n")
    out.write(f"// SHA-256: {sha256}\n")
    out.write("#pragma once\n")
    out.write("#include <cstddef>\n")
    out.write("#include <cstdint>\n")
    out.write(f"static const std::size_t kCorpusSize     = {n};\n")
    out.write(f'static const char        kCorpusSHA256[] = "{sha256}";\n')
    out.write("static const uint8_t kCorpusData[] = {\n")
    for i in range(0, n, 16):
        chunk = data[i : i + 16]
        out.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    out.write("};\n")

print(f"[gen_corpus_header] {dst_path} ({n} bytes, sha256={sha256[:16]}...)")
